services:
  db:
    image: mysql:lts
    container_name: service-db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - '3306:3306'
    volumes:
      - ./api-volume/db/data:/var/lib/mysql
    restart: always
